--- ============================================
-- FairMoney OLAP Data Warehouse Schema 
-- ============================================
CREATE SCHEMA IF NOT EXISTS reporting;

CREATE TABLE reporting.dim_customer (
  customer_key integer NOT NULL DEFAULT nextval('reporting.dim_customer_customer_key_seq'::regclass),
  customer_id integer NOT NULL,
  country_code character varying NOT NULL,
  country_name character varying NOT NULL,
  currency_code character varying NOT NULL,
  customer_name character varying NOT NULL,
  phone_number character varying,
  email character varying,
  date_of_birth date,
  age_group character varying,
  customer_status character varying NOT NULL,
  customer_segment character varying,
  registration_year integer,
  registration_month integer,
  registration_cohort character varying,
  kyc_status character varying,
  kyc_verified_date date,
  effective_date date NOT NULL,
  end_date date,
  is_current boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT dim_customer_pkey PRIMARY KEY (customer_key)
);
CREATE TABLE reporting.dim_date (
  date_key integer NOT NULL,
  full_date date NOT NULL UNIQUE,
  year integer NOT NULL,
  quarter integer NOT NULL,
  month integer NOT NULL,
  day integer NOT NULL,
  day_name character varying NOT NULL,
  month_name character varying NOT NULL,
  quarter_name character varying NOT NULL,
  year_month character varying NOT NULL,
  year_quarter character varying NOT NULL,
  is_weekend boolean NOT NULL,
  is_month_end boolean NOT NULL,
  is_quarter_end boolean NOT NULL,
  is_year_end boolean NOT NULL,
  fiscal_year integer,
  fiscal_quarter integer,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT dim_date_pkey PRIMARY KEY (date_key)
);
CREATE TABLE reporting.dim_loan (
  loan_key integer NOT NULL DEFAULT nextval('reporting.dim_loan_loan_key_seq'::regclass),
  loan_id integer NOT NULL UNIQUE,
  loan_number character varying NOT NULL,
  loan_status character varying NOT NULL,
  loan_type character varying,
  vintage_year integer,
  vintage_month integer,
  vintage_cohort character varying,
  maturity_year integer,
  maturity_month integer,
  tenure_days integer,
  tenure_months integer,
  tenure_tier character varying,
  is_first_loan boolean,
  customer_loan_sequence integer,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT dim_loan_pkey PRIMARY KEY (loan_key)
);
CREATE TABLE reporting.dim_payment_method (
  payment_method_key integer NOT NULL DEFAULT nextval('reporting.dim_payment_method_payment_method_key_seq'::regclass),
  payment_method character varying NOT NULL UNIQUE,
  payment_channel character varying,
  payment_category character varying,
  is_digital boolean DEFAULT false,
  processing_fee_rate numeric DEFAULT 0,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT dim_payment_method_pkey PRIMARY KEY (payment_method_key)
);
CREATE TABLE reporting.dim_product (
  product_key integer NOT NULL DEFAULT nextval('reporting.dim_product_product_key_seq'::regclass),
  product_id integer NOT NULL UNIQUE,
  country_code character varying NOT NULL,
  country_name character varying NOT NULL,
  product_name character varying NOT NULL,
  product_code character varying NOT NULL,
  product_category character varying,
  min_amount numeric NOT NULL,
  max_amount numeric NOT NULL,
  amount_tier character varying,
  min_tenure_days integer NOT NULL,
  max_tenure_days integer NOT NULL,
  tenure_tier character varying,
  interest_rate numeric NOT NULL,
  interest_tier character varying,
  processing_fee_rate numeric,
  risk_tier character varying,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT dim_product_pkey PRIMARY KEY (product_key)
);
CREATE TABLE reporting.fact_collections (
  collection_key integer NOT NULL DEFAULT nextval('reporting.fact_collections_collection_key_seq'::regclass),
  assignment_date_key integer NOT NULL,
  customer_key integer NOT NULL,
  loan_key integer NOT NULL,
  collection_id integer NOT NULL,
  assigned_agent character varying,
  case_status character varying NOT NULL,
  priority_level character varying,
  outstanding_at_assignment numeric,
  days_past_due_at_assignment integer,
  case_duration_days integer DEFAULT 0,
  resolution_date_key integer,
  amount_recovered numeric DEFAULT 0,
  recovery_rate numeric DEFAULT 0,
  is_resolved boolean DEFAULT false,
  is_successful_recovery boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fact_collections_pkey PRIMARY KEY (collection_key),
  CONSTRAINT fact_collections_assignment_date_key_fkey FOREIGN KEY (assignment_date_key) REFERENCES reporting.dim_date(date_key),
  CONSTRAINT fact_collections_customer_key_fkey FOREIGN KEY (customer_key) REFERENCES reporting.dim_customer(customer_key),
  CONSTRAINT fact_collections_loan_key_fkey FOREIGN KEY (loan_key) REFERENCES reporting.dim_loan(loan_key),
  CONSTRAINT fact_collections_resolution_date_key_fkey FOREIGN KEY (resolution_date_key) REFERENCES reporting.dim_date(date_key)
);
CREATE TABLE reporting.fact_loan_applications (
  application_key integer NOT NULL DEFAULT nextval('reporting.fact_loan_applications_application_key_seq'::regclass),
  application_date_key integer NOT NULL,
  customer_key integer NOT NULL,
  product_key integer NOT NULL,
  application_id integer NOT NULL,
  application_number character varying,
  requested_amount numeric NOT NULL,
  requested_tenure_days integer NOT NULL,
  application_status character varying NOT NULL,
  risk_score numeric,
  is_approved boolean DEFAULT false,
  is_rejected boolean DEFAULT false,
  is_disbursed boolean DEFAULT false,
  is_repeat_customer boolean DEFAULT false,
  processing_time_hours integer,
  approval_date_key integer,
  disbursement_date_key integer,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fact_loan_applications_pkey PRIMARY KEY (application_key),
  CONSTRAINT fact_loan_applications_application_date_key_fkey FOREIGN KEY (application_date_key) REFERENCES reporting.dim_date(date_key),
  CONSTRAINT fact_loan_applications_customer_key_fkey FOREIGN KEY (customer_key) REFERENCES reporting.dim_customer(customer_key),
  CONSTRAINT fact_loan_applications_product_key_fkey FOREIGN KEY (product_key) REFERENCES reporting.dim_product(product_key),
  CONSTRAINT fact_loan_applications_approval_date_key_fkey FOREIGN KEY (approval_date_key) REFERENCES reporting.dim_date(date_key),
  CONSTRAINT fact_loan_applications_disbursement_date_key_fkey FOREIGN KEY (disbursement_date_key) REFERENCES reporting.dim_date(date_key)
);
CREATE TABLE reporting.fact_loan_portfolio (
  portfolio_key integer NOT NULL DEFAULT nextval('reporting.fact_loan_portfolio_portfolio_key_seq'::regclass),
  date_key integer NOT NULL,
  customer_key integer NOT NULL,
  product_key integer NOT NULL,
  loan_key integer NOT NULL,
  principal_amount numeric NOT NULL,
  interest_amount numeric NOT NULL,
  total_loan_amount numeric NOT NULL,
  outstanding_principal numeric DEFAULT 0,
  outstanding_interest numeric DEFAULT 0,
  total_outstanding numeric DEFAULT 0,
  total_paid_amount numeric DEFAULT 0,
  principal_paid numeric DEFAULT 0,
  interest_paid numeric DEFAULT 0,
  days_past_due integer DEFAULT 0,
  dpd_bucket character varying,
  is_current boolean DEFAULT true,
  is_overdue boolean DEFAULT false,
  is_defaulted boolean DEFAULT false,
  ever_30_dpd boolean DEFAULT false,
  ever_60_dpd boolean DEFAULT false,
  ever_90_dpd boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fact_loan_portfolio_pkey PRIMARY KEY (portfolio_key),
  CONSTRAINT fact_loan_portfolio_date_key_fkey FOREIGN KEY (date_key) REFERENCES reporting.dim_date(date_key),
  CONSTRAINT fact_loan_portfolio_customer_key_fkey FOREIGN KEY (customer_key) REFERENCES reporting.dim_customer(customer_key),
  CONSTRAINT fact_loan_portfolio_product_key_fkey FOREIGN KEY (product_key) REFERENCES reporting.dim_product(product_key),
  CONSTRAINT fact_loan_portfolio_loan_key_fkey FOREIGN KEY (loan_key) REFERENCES reporting.dim_loan(loan_key)
);
CREATE TABLE reporting.fact_payments (
  payment_key integer NOT NULL DEFAULT nextval('reporting.fact_payments_payment_key_seq'::regclass),
  payment_date_key integer NOT NULL,
  customer_key integer NOT NULL,
  product_key integer NOT NULL,
  loan_key integer NOT NULL,
  payment_method_key integer NOT NULL,
  payment_id integer NOT NULL,
  payment_reference character varying,
  payment_amount numeric NOT NULL,
  payment_type character varying NOT NULL,
  payment_status character varying NOT NULL,
  is_successful boolean DEFAULT true,
  is_on_time boolean DEFAULT true,
  is_early_payment boolean DEFAULT false,
  is_late_payment boolean DEFAULT false,
  days_late integer DEFAULT 0,
  original_payment_date timestamp without time zone,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fact_payments_pkey PRIMARY KEY (payment_key),
  CONSTRAINT fact_payments_payment_date_key_fkey FOREIGN KEY (payment_date_key) REFERENCES reporting.dim_date(date_key),
  CONSTRAINT fact_payments_customer_key_fkey FOREIGN KEY (customer_key) REFERENCES reporting.dim_customer(customer_key),
  CONSTRAINT fact_payments_product_key_fkey FOREIGN KEY (product_key) REFERENCES reporting.dim_product(product_key),
  CONSTRAINT fact_payments_loan_key_fkey FOREIGN KEY (loan_key) REFERENCES reporting.dim_loan(loan_key),
  CONSTRAINT fact_payments_payment_method_key_fkey FOREIGN KEY (payment_method_key) REFERENCES reporting.dim_payment_method(payment_method_key)
);
